import fs from 'node:fs';
import assert from 'node:assert/strict';
import {RandomMath as E} from '../dist/index.js';
import * as P from '../dist/pool-model.js';
import {readInspection} from '../dist/pool-runtime.js';
const original=Math.random;let passed=0,failed=0;const warn=console.warn;console.warn=()=>{};
async function test(name,fn){try{Math.random=()=>.25;await fn();passed++;console.log('PASS '+name);}catch(e){failed++;console.error('FAIL '+name+': '+e.stack);}}
const spec={id:'events',name:'事件',kind:'without',valueType:'text',probability:'weight',quantityWeight:'candidate',random:'fixed'};
const rows=[{poolId:'events',id:'a',label:'A',value:'A',rate:'1',quantity:10},{poolId:'events',id:'b',label:'B',value:'B',rate:'1',quantity:1}];
const fields={outVar:'value',idVar:'id',valuesVar:'values',idsVar:'ids',reportVar:'report',receiptVar:'receipt',remainingVar:'remaining',availableVar:'available',successVar:'ok',errorVar:'error',statusVar:'status'};
function host(config={},state,extra={}){
 const values=new Map(Object.entries({value:'old',id:'old',values:'old',ids:'old',report:'',receipt:'',remaining:0,available:0,ok:true,error:'',status:'',gate:true,power:2,n:0,...extra}));
 const saved=new Map(Object.entries(state??{drawDecks:[],fixedResults:[],poolStateV3:''}));const abort=new AbortController();let resolveUI,shown;let onShow;
 const settings={pools:[spec],candidates:rows,adjustments:[],...config};
 const owner={save:{get:k=>saved.get(k),set:(k,v)=>saved.set(k,structuredClone(v))}};
 const ctx={variables:{get:k=>values.get(k),set:(k,v)=>{assert.notEqual(v,undefined);values.set(k,v);}},settings:{get:k=>settings[k]},flow:{signal:abort.signal},database:{collection:()=>({find:async()=>[]})},dialogue:{setSkipMode(v){assert.equal(v,false)},setAutoMode(v){assert.equal(v,false)}},system:{invoke:async(slot,payload,options)=>{assert.equal(slot,'internal.system.choice');assert.equal(options.modal,true);shown=payload;const pending=new Promise(resolve=>{resolveUI=resolve;});if(onShow)queueMicrotask(()=>{Promise.resolve(onShow(payload)).catch(e=>{resolveUI();throw e;});});await pending;},close:async()=>resolveUI?.()}};
 return {ctx,owner,saved,values,settings,abort,get shown(){return shown},onShow(fn){onShow=fn},run:(name,p={})=>E[name].run.call(owner,ctx,p),immediate:(name,p={})=>E[name].runImmediately.call(owner,ctx,p),state:()=>P.decode(saved.get('poolStateV3')),snapshot:()=>Object.fromEntries([...saved].map(([k,v])=>[k,structuredClone(v)]))};
}

await test('closed choice callback is inert after completion',async()=>{const h=host();let old;h.onShow(ui=>{old=ui.onSelect;return h.ctx.system.close();});await h.run('playerChoice',{poolId:'events',...fields});const state=h.snapshot(),values=[...h.values];await old(0);assert.deepEqual(h.snapshot(),state);assert.deepEqual([...h.values],values);});
await test('old callback cannot consume or close a reopened same-key choice',async()=>{const h=host();let old,firstRequest;h.onShow(ui=>{old=ui.onSelect;firstRequest=h.state().pendingChoices[0].requestId;return h.ctx.system.close();});await h.run('playerChoice',{poolId:'events',...fields});h.onShow(async ui=>{assert.notEqual(h.state().pendingChoices[0].requestId,firstRequest);const state=h.snapshot(),values=[...h.values];await old(0);assert.deepEqual(h.snapshot(),state);assert.deepEqual([...h.values],values);assert.equal(h.state().pendingChoices.length,1);await ui.onSelect(1);});await h.run('playerChoice',{poolId:'events',...fields});assert.equal(h.values.get('status'),'ok');assert.equal(h.values.get('value'),'B');assert.deepEqual(h.state().pools[0].items.map(c=>c.remaining),[10,0]);});
await test('legacy single draw ignores stored batch prefix before and after adoption',async()=>{const h=host({pools:[],candidates:[]});await h.run('deckCreate',{key:'old',source:'array',arrayJson:'["A","B","C","D"]',mode:'fixed',valueType:'text'});const params={key:'old',count:1,prefix:'not_declared',outVar:'value',successVar:'ok',errorVar:'error'};assert.equal(JSON.parse(await h.run('deckDraw',params)).length,1);await h.run('drawWithout',{poolId:'old',...fields});assert.equal(JSON.parse(await h.run('deckDraw',params)).length,1);assert.equal(h.values.get('ok'),true);assert.equal(h.state().pools[0].legacy.drawn,3);});
await test('idempotent initialization preserves an occupied pool for every initializer',async()=>{const h=host();await h.run('drawWithout',{poolId:'events',consumption:'deferred',...fields});const before=h.snapshot();for(const action of ['initialize','import-array','import-table']){await h.run('poolUpdate',{poolId:'events',action,...fields});assert.equal(h.values.get('status'),'ok');assert.deepEqual(h.snapshot(),before);}for(const action of ['reset','delete']){await h.run('poolUpdate',{poolId:'events',action,...fields});assert.equal(h.values.get('status'),'error');assert.deepEqual(h.snapshot(),before);}});
await test('orphan candidate identifies its row, candidate and missing pool',()=>{const h=host({candidates:[{...rows[0],poolId:'typo'}]});const r=readInspection(h.owner,h.ctx,'events');assert.equal(r.errorCode,'INVALID_CONFIG');assert.match(r.message,/a/);assert.match(r.message,/typo/);assert.equal(h.saved.get('poolStateV3'),'');});
await test('invalid author config does not overwrite an already initialized runtime pool',async()=>{const h=host();await h.run('poolUpdate',{action:'initialize',poolId:'events'});h.settings.candidates=[...h.settings.candidates,{...rows[0],poolId:'typo'}];await h.run('drawWithout',{poolId:'events',...fields});assert.equal(h.values.get('status'),'ok');assert.equal(readInspection(h.owner,h.ctx,'events').errorCode,'INVALID_CONFIG');});
await test('configuration fingerprint is retained until explicit reset',async()=>{const h=host();await h.run('poolUpdate',{action:'initialize',poolId:'events'});const v=h.state().pools[0].configVersion;assert.match(v,/^cfg1-/);h.settings.candidates=rows.map(c=>({...c,rate:'2'}));await h.run('poolUpdate',{action:'add-quantity',poolId:'events',candidateId:'a',amount:1});assert.equal(h.state().pools[0].configVersion,v);await h.run('poolUpdate',{action:'reset',poolId:'events'});assert.notEqual(h.state().pools[0].configVersion,v);assert.equal(h.state().pools[0].configSource,'settings');});
await test('old v3 saves without configuration or request fingerprints remain readable',async()=>{const h=host();let snap;h.onShow(()=>{snap=h.snapshot();h.abort.abort();});await h.run('playerChoice',{poolId:'events',...fields});const state=JSON.parse(snap.poolStateV3);delete state.pools[0].configVersion;delete state.pools[0].configSource;delete state.pendingChoices[0].requestId;snap.poolStateV3=JSON.stringify(state);const loaded=host({},snap);assert.equal(readInspection(loaded.owner,loaded.ctx,'events').details.configVersion,'UNKNOWN');loaded.onShow(ui=>ui.onSelect(1));await loaded.immediate('playerChoice',{poolId:'events',...fields});assert.equal(loaded.values.get('status'),'ok');assert.equal(loaded.values.get('value'),'B');});
await test('replacement and temporary batch forms omit unusable receipt fields',()=>{assert.equal(E.drawReplace.schema.receiptVar,undefined);assert.equal(E.drawReplace.schema.remainingVar,undefined);assert.equal(E.drawWithout.schema.batch__receiptVar,undefined);});
await test('human examples run sequentially through variables, reload, confirmation and feedback',async()=>{const examples=JSON.parse(fs.readFileSync(new URL('../docs/examples-v3.json',import.meta.url)));const extra={result:'',candidate:'',left:0,event_completed:false,archive_open:false};const h=host(examples.settings,undefined,extra);await h.run('drawReplace',{poolId:'weather',count:3,valuesVar:'values',statusVar:'status'});assert.equal(JSON.parse(h.values.get('values')).length,3);await h.run('drawWithout',{poolId:'bag',count:1,consumption:'deferred',idVar:'candidate',receiptVar:'receipt',statusVar:'status'});const receipt=h.values.get('receipt');assert.equal(h.state().pools.find(p=>p.id==='bag').items.reduce((n,c)=>n+c.reserved,0),1);const loaded=host(examples.settings,h.snapshot(),Object.fromEntries(h.values));await loaded.run('drawWithout',{action:'confirm',receiptId:receipt,...fields});assert.equal(loaded.state().pools.find(p=>p.id==='bag').items.reduce((n,c)=>n+c.remaining,0),10);loaded.onShow(ui=>{assert.deepEqual(ui.choices.map(c=>c.text),['调查庭院','休息']);return ui.onSelect(1);});await loaded.run('playerChoice',{poolId:'events',idVar:'candidate',outVar:'result',statusVar:'status'});assert.equal(loaded.values.get('candidate'),'c');await loaded.run('poolUpdate',{poolId:'reward',action:'add-rate',candidateId:loaded.values.get('candidate'),amount:2,when:'event_completed',statusVar:'status'});assert.equal(loaded.values.get('status'),'skipped');assert.equal(loaded.state().pools.some(p=>p.id==='reward'),false);loaded.values.set('event_completed',true);await loaded.run('poolUpdate',{poolId:'reward',action:'add-rate',candidateId:loaded.values.get('candidate'),amount:2,when:'event_completed',statusVar:'status'});assert.equal(loaded.values.get('status'),'ok');assert.equal(loaded.state().pools.find(p=>p.id==='reward').items.find(c=>c.id==='c').rate,3);});
await test('weight expressions follow current numeric variables in initialized with/without pools and after reload',async()=>{
 for(const kind of ['with','without']){
  const h=host({pools:[{...spec,kind}],candidates:rows.map((c,i)=>({...c,rate:i?'10':'var("好感度")',quantity:10}))},undefined,{'好感度':10});
  await h.run('poolUpdate',{poolId:'events',action:'initialize',...fields});
  const before=h.snapshot();assert.deepEqual(readInspection(h.owner,h.ctx,'events').details.candidates.map(c=>c.probability),[.5,.5]);
  h.values.set('好感度',30);assert.deepEqual(readInspection(h.owner,h.ctx,'events').details.candidates.map(c=>c.probability),[.75,.25]);assert.deepEqual(h.snapshot(),before);
  const loaded=host(h.settings,h.snapshot(),Object.fromEntries(h.values));loaded.values.set('好感度',0);
  await loaded.run(kind==='with'?'drawReplace':'drawWithout',{poolId:'events',count:1,...fields});
  assert.equal(loaded.values.get('status'),'ok');assert.equal(loaded.values.get('id'),'b');assert.equal(loaded.state().pools[0].items[0].rate,'var("好感度")');
 }
});
await test('set-rate retains a variable expression while add-rate evaluates once; invalid variable input rolls back',async()=>{
 const h=host();await h.run('poolUpdate',{poolId:'events',action:'set-rate',candidateId:'a',amount:'var("power") + 10',...fields});
 h.values.set('power',30);assert.equal(readInspection(h.owner,h.ctx,'events').details.candidates[0].base,40);
 await h.run('poolUpdate',{poolId:'events',action:'add-rate',candidateId:'a',amount:'var("power")',...fields});assert.equal(h.state().pools[0].items[0].rate,70);
 h.values.set('power',5);assert.equal(readInspection(h.owner,h.ctx,'events').details.candidates[0].base,70);
 for(const amount of ['var("missing")','var("value")','-1']){const before=h.snapshot();await h.run('poolUpdate',{poolId:'events',action:'set-rate',candidateId:'a',amount,...fields});assert.equal(h.values.get('status'),'error');assert.deepEqual(h.snapshot(),before);}
 await h.run('poolUpdate',{poolId:'events',action:'set-rate',candidateId:'a',amount:'var("power")',...fields});h.values.set('power',-1);const before=h.snapshot();await h.run('drawWithout',{poolId:'events',...fields});assert.equal(h.values.get('status'),'error');assert.deepEqual(h.snapshot(),before);
});
await test('percentage expressions follow variables but enforce total 100 before any consumption',async()=>{
 const h=host({pools:[{...spec,probability:'percent'}],candidates:rows.map((c,i)=>({...c,rate:i?'100 - var("power")':'var("power")'}))});
 h.values.set('power',20);assert.deepEqual(readInspection(h.owner,h.ctx,'events').details.candidates.map(c=>c.base),[20,80]);
 await h.run('poolUpdate',{poolId:'events',action:'initialize',...fields});h.values.set('power',70);assert.deepEqual(readInspection(h.owner,h.ctx,'events').details.candidates.map(c=>c.base),[70,30]);
 h.values.set('power',101);const before=h.snapshot();await h.run('drawWithout',{poolId:'events',...fields});assert.equal(h.values.get('status'),'error');assert.deepEqual(h.snapshot(),before);
});
console.warn=warn;Math.random=original;console.log(JSON.stringify({passed,failed,scope:'SDK shim; not real Studio/player'}));if(failed)process.exitCode=1;
