import fs from 'node:fs';
import assert from 'node:assert/strict';
import {RandomMath as E} from '../dist/index.js';
import * as P from '../dist/pool-model.js';
import {readInspection} from '../dist/pool-runtime.js';
const original=Math.random;let passed=0,failed=0;const warn=console.warn;console.warn=()=>{};
async function test(name,fn){try{Math.random=()=>.25;await fn();passed++;console.log('PASS '+name);}catch(e){failed++;console.error('FAIL '+name+': '+e.stack);}}
const spec={id:'events',name:'事件',kind:'without',valueType:'text',probability:'weight',quantityWeight:'candidate',random:'fixed'};
const rows=[{poolId:'events',id:'a',label:'A',value:'A',rate:'1',quantity:10},{poolId:'events',id:'b',label:'B',value:'B',rate:'1',quantity:1}];
const fields={outVar:'value',idVar:'id',valuesVar:'values',idsVar:'ids',reportVar:'report',receiptVar:'receipt',remainingVar:'remaining',availableVar:'available',successVar:'ok',errorVar:'error',statusVar:'status'};
function host(config={},state,extra={}){
 const values=new Map(Object.entries({value:'old',id:'old',values:'old',ids:'old',report:'',receipt:'',remaining:0,available:0,ok:true,error:'',status:'',gate:true,power:2,n:0,...extra}));
 const saved=new Map(Object.entries(state??{drawDecks:[],fixedResults:[],poolStateV3:''}));const abort=new AbortController();let resolveUI,shown;let onShow;
 const settings={pools:[spec],candidates:rows,adjustments:[],...config};
 const owner={save:{get:k=>saved.get(k),set:(k,v)=>saved.set(k,structuredClone(v))}};
 const ctx={variables:{get:k=>values.get(k),set:(k,v)=>{assert.notEqual(v,undefined);values.set(k,v);}},settings:{get:k=>settings[k]},flow:{signal:abort.signal},database:{collection:()=>({find:async()=>[]})},dialogue:{setSkipMode(v){assert.equal(v,false)},setAutoMode(v){assert.equal(v,false)}},system:{invoke:async(slot,payload,options)=>{assert.equal(slot,'internal.system.choice');assert.equal(options.modal,true);shown=payload;const pending=new Promise(resolve=>{resolveUI=resolve;});if(onShow)queueMicrotask(()=>{Promise.resolve(onShow(payload)).catch(e=>{resolveUI();throw e;});});await pending;},close:async()=>resolveUI?.()}};
 return {ctx,owner,saved,values,settings,abort,get shown(){return shown},onShow(fn){onShow=fn},run:(name,p={})=>E[name].run.call(owner,ctx,p),immediate:(name,p={})=>E[name].runImmediately.call(owner,ctx,p),state:()=>P.decode(saved.get('poolStateV3')),snapshot:()=>Object.fromEntries([...saved].map(([k,v])=>[k,structuredClone(v)]))};
}
const pure=(config={},items=rows)=>P.configuredPool({...spec,...config},items,42);
await test('six visible methods; eight legacy definitions remain callable',()=>{const methods=Object.values(E).filter(x=>x&&typeof x==='object'&&typeof x.run==='function');assert.deepEqual(methods.filter(x=>!x.enabledWhen).map(x=>x.title),['随机数','放回抽取','不放回抽取','调整抽取池','玩家选项','计算']);assert.equal(methods.filter(x=>x.enabledWhen==='showLegacyMethods').length,8);for(const m of methods)for(const f of Object.values(m.schema??{}))if(f.visibleWhen)assert.ok(m.schema[f.visibleWhen.field]);for(const m of [E.drawReplace,E.drawWithout,E.poolUpdate,E.playerChoice])assert.equal(m.returns,undefined);});
await test('candidate quantity rule is 50/50',()=>assert.deepEqual(P.distribution(pure(),()=>true).map(x=>x.probability),[.5,.5]));
await test('unit quantity rule is 10/11 and 1/11',()=>{const d=P.distribution(pure({quantityWeight:'unit'}),()=>true);assert.ok(Math.abs(d[0].probability-10/11)<1e-12);});
await test('20/30/50 becomes 40/60 when third condition is false',()=>{const p=pure({probability:'percent'},[{id:'a',rate:20,quantity:1},{id:'b',rate:30,quantity:1},{id:'c',rate:50,condition:'gate',quantity:1}]);P.distribution(p,()=>false).forEach((x,i)=>assert.ok(Math.abs(x.probability-[.4,.6,0][i])<1e-12));});
await test('percentage initial sum and unknown condition fail explicitly',()=>{assert.throws(()=>P.distribution(pure({probability:'percent'}),()=>true),/100/);assert.throws(()=>P.distribution(pure({},[{id:'a',condition:'missing'}]),()=>undefined),/布尔/);});
await test('new percent value redistributes remaining candidates',()=>{const p=pure({probability:'percent'},[{id:'a',rate:20},{id:'b',rate:30},{id:'c',rate:50}]);P.adjust(p,[{op:'set-percent',candidateId:'a',amount:40}],()=>true);assert.deepEqual(p.items.map(x=>x.rate),[40,22.5,37.5]);});
await test('simultaneous percentage edits assign 40/40/20',()=>{const p=pure({probability:'percent'},[{id:'a',rate:20},{id:'b',rate:30},{id:'c',rate:50}]);P.adjust(p,[{op:'set-percent',candidateId:'a',amount:40},{op:'set-percent',candidateId:'b',amount:40}],()=>true);assert.deepEqual(p.items.map(x=>x.rate),[40,40,20]);});
await test('duplicate labels retain separate IDs',()=>{const p=pure({},[{id:'a',value:'same'},{id:'b',value:'same'}]);const s=P.blankStore();s.pools=[p];const r=P.draw(s,p,2,()=>true);assert.deepEqual(r.items.map(x=>x.value),['same','same']);assert.equal(new Set(r.items.map(x=>x.id)).size,2);});
await test('auto initialization and replacement retain candidates',async()=>{const h=host({pools:[{...spec,kind:'with'}]});await h.run('drawReplace',{poolId:'events',count:5,...fields});assert.equal(h.values.get('status'),'ok');assert.equal(JSON.parse(h.values.get('values')).length,5);assert.equal(h.state().pools[0].items.length,2);assert.equal(h.state().pools[0].items[0].remaining,0);});
await test('exhaustion never automatically refills',async()=>{const h=host({candidates:[{...rows[0],quantity:1}]});await h.run('drawWithout',{poolId:'events',...fields});const before=h.saved.get('poolStateV3');await h.run('drawWithout',{poolId:'events',...fields});assert.equal(h.values.get('status'),'empty');assert.equal(h.saved.get('poolStateV3'),before);});
await test('wrong draw entry does not initialize state',async()=>{const h=host();await h.run('drawReplace',{poolId:'events',...fields});assert.equal(h.values.get('status'),'error');assert.equal(h.saved.get('poolStateV3'),'');});
await test('prefixed operation fields resolve to runtime parameters',async()=>{const h=host();await h.run('drawWithout',{action:'draw','draw__poolId':'events','draw__count':1,'draw__outVar':'value',...fields});assert.equal(h.values.get('ok'),true);assert.equal(h.values.get('remaining'),10);});
await test('inspection is read only and does not use random',async()=>{const h=host();Math.random=()=>{throw Error('read sampled')};const before=h.snapshot();await h.run('poolUpdate',{poolId:'events',action:'inspect',...fields});assert.equal(h.values.get('status'),'ok');assert.deepEqual(h.snapshot(),before);assert.equal(readInspection(h.owner,h.ctx,'events').details.candidates.length,2);});
await test('false adjustment condition does not initialize',async()=>{const h=host({},undefined,{gate:false});await h.run('poolUpdate',{action:'add-quantity',poolId:'events',candidateId:'a',amount:'1',when:'gate',...fields});assert.equal(h.values.get('status'),'skipped');assert.equal(h.saved.get('poolStateV3'),'');});
await test('batch adjustment rolls back on a later invalid candidate',async()=>{const h=host({adjustments:[{batchId:'x',op:'add-quantity',candidateId:'a',amount:'2'},{batchId:'x',op:'remove',candidateId:'absent'}]});await h.run('poolUpdate',{action:'initialize',poolId:'events'});const before=h.snapshot();await h.run('poolUpdate',{action:'batch-adjust',batchId:'x',poolId:'events',...fields});assert.equal(h.values.get('status'),'error');assert.deepEqual(h.snapshot(),before);});
await test('batch can take candidate ID and amount from story variables',async()=>{const h=host({adjustments:[{batchId:'x',op:'add-quantity',candidateIdVar:'id',amount:'var("power")'}]},undefined,{id:'a'});await h.run('poolUpdate',{action:'batch-adjust',batchId:'x',poolId:'events',...fields});assert.equal(h.state().pools[0].items[0].remaining,12);});
await test('deferred reserves then confirms exactly once',async()=>{const h=host({candidates:[{...rows[0],quantity:2}]});await h.run('drawWithout',{poolId:'events',consumption:'deferred',...fields});const rid=h.values.get('receipt');assert.equal(h.values.get('remaining'),2);assert.equal(h.values.get('available'),1);await h.run('drawWithout',{action:'confirm',receiptId:rid,...fields});assert.equal(h.values.get('remaining'),1);const before=h.snapshot();await h.run('drawWithout',{action:'confirm',receiptId:rid,...fields});assert.deepEqual(h.snapshot(),before);await h.run('drawWithout',{action:'cancel',receiptId:rid,...fields});assert.equal(h.values.get('status'),'error');});
await test('cancel releases once without rewinding random',async()=>{const h=host();await h.run('drawWithout',{poolId:'events',consumption:'deferred',...fields});const rid=h.values.get('receipt'),cursor=h.state().pools[0].cursor;await h.run('drawWithout',{action:'cancel',receiptId:rid,...fields});assert.equal(h.state().pools[0].cursor,cursor);assert.equal(h.state().pools[0].items.reduce((n,x)=>n+x.reserved,0),0);const before=h.snapshot();await h.run('drawWithout',{action:'cancel',receiptId:rid,...fields});assert.deepEqual(h.snapshot(),before);});
await test('pending receipt survives slot reload',async()=>{const h=host();await h.run('drawWithout',{poolId:'events',consumption:'deferred',...fields});const next=host({},h.snapshot());await next.run('drawWithout',{action:'confirm',receiptId:h.values.get('receipt'),...fields});assert.equal(next.values.get('remaining'),10);});
await test('reserved candidate cannot be removed or reduced below reserved',async()=>{const h=host({candidates:[{...rows[0],quantity:1}]});await h.run('drawWithout',{poolId:'events',consumption:'deferred',...fields});const before=h.snapshot();for(const [action,amount]of [['remove',0],['set-quantity',0]]){await h.run('poolUpdate',{poolId:'events',action,candidateId:'a',amount,...fields});assert.equal(h.values.get('status'),'error');assert.deepEqual(h.snapshot(),before);}});
await test('pending receipt prevents reset and delete',async()=>{const h=host();await h.run('drawWithout',{poolId:'events',consumption:'deferred',...fields});const before=h.snapshot();for(const action of ['reset','delete']){await h.run('poolUpdate',{poolId:'events',action,...fields});assert.equal(h.values.get('status'),'error');assert.deepEqual(h.snapshot(),before);}});
await test('fixed state resumes across independent owner instances',async()=>{const h=host();await h.run('poolUpdate',{poolId:'events',action:'initialize'});const snap=h.snapshot();Math.random=()=>0;await h.run('drawWithout',{poolId:'events',count:5,...fields});const loaded=host({},snap);Math.random=()=>.999;await loaded.run('drawWithout',{poolId:'events',count:5,...fields});assert.equal(loaded.values.get('values'),h.values.get('values'));assert.equal(loaded.saved.get('poolStateV3'),h.saved.get('poolStateV3'));});
await test('fresh mode can reroll same saved state',async()=>{const cfg={pools:[{...spec,random:'fresh'}]};const h=host(cfg);await h.run('poolUpdate',{poolId:'events',action:'initialize'});const snap=h.snapshot();Math.random=()=>0;await h.run('drawWithout',{poolId:'events',...fields});const loaded=host(cfg,snap);Math.random=()=>.999;await loaded.run('drawWithout',{poolId:'events',...fields});assert.notEqual(loaded.values.get('value'),h.values.get('value'));});
await test('slot independence and no cross-slot shared state',async()=>{const a=host(),b=host();await a.run('drawWithout',{poolId:'events'});assert.equal(b.saved.get('poolStateV3'),'');assert.equal(E.saveSchema.poolStateV3.persistence,'slot');});
await test('add after depletion works without resetting old quantities',async()=>{const h=host({candidates:[{...rows[0],quantity:1}]});await h.run('drawWithout',{poolId:'events'});await h.run('poolUpdate',{poolId:'events',action:'add',candidateId:'c',label:'C',value:'C',rate:'1',quantity:2,...fields});assert.equal(h.state().pools[0].items[0].remaining,0);await h.run('drawWithout',{poolId:'events',...fields});assert.equal(h.values.get('value'),'C');});
await test('updates preserve author configuration',async()=>{const h=host();const before=structuredClone(h.settings);await h.run('poolUpdate',{poolId:'events',action:'set-rate',candidateId:'a',amount:'9'});assert.deepEqual(h.settings,before);});
await test('quantity and negative rate errors preserve state',async()=>{const h=host();for(const p of [{action:'set-quantity',amount:'1.5'},{action:'set-quantity',amount:'-1'},{action:'set-rate',amount:'-2'}]){const before=h.snapshot();await h.run('poolUpdate',{poolId:'events',candidateId:'a',...p,...fields});assert.equal(h.values.get('status'),'error');assert.deepEqual(h.snapshot(),before);}});
await test('wrong or missing output types fail before committing pool',async()=>{const h=host();for(const p of [{outVar:'n'},{outVar:'missing'},{outVar:'value',reportVar:'value'}]){await h.run('drawWithout',{poolId:'events',...fields,...p});assert.equal(h.saved.get('poolStateV3'),'');assert.equal(h.values.get('value'),'old');}});
await test('output setter fault rolls back quantities and previous values',async()=>{const h=host();await h.run('poolUpdate',{poolId:'events',action:'initialize'});const before=h.snapshot();const setter=h.ctx.variables.set;h.ctx.variables.set=(k,v)=>{if(k==='ids')throw Error('injected');setter(k,v);};await h.run('drawWithout',{poolId:'events',...fields});assert.deepEqual(h.snapshot(),before);assert.equal(h.values.get('value'),'old');});
await test('large invalid count rejected without allocating batch',async()=>{const h=host();await h.run('drawWithout',{poolId:'events',count:1e9,...fields});assert.equal(h.saved.get('poolStateV3'),'');assert.equal(h.values.get('status'),'error');});
await test('restoration replay does not redraw or adjust',async()=>{const h=host();await h.run('drawWithout',{poolId:'events',...fields});const before=h.snapshot();await h.immediate('drawWithout',{poolId:'events',...fields});await h.immediate('poolUpdate',{action:'add-quantity',poolId:'events',candidateId:'a',amount:99});assert.deepEqual(h.snapshot(),before);});
await test('temporary batch is without replacement only within that call',async()=>{const h=host();for(let i=0;i<2;i++){await h.run('drawWithout',{action:'batch',poolId:'temp',arrayJson:'["A","B"]',count:2,...fields});assert.deepEqual(JSON.parse(h.values.get('values')).sort(),['A','B']);}assert.equal(h.saved.get('poolStateV3'),'');});
await test('numeric results and custom data cross the result boundary',async()=>{const h=host({pools:[{...spec,valueType:'number'}],candidates:[{...rows[0],value:'var("power")*2',data:'{"trait":"merchant"}'}]});await h.run('drawWithout',{poolId:'events',...fields,outVar:'n'});assert.equal(h.values.get('n'),4);assert.equal(JSON.parse(h.values.get('report')).items[0].data.trait,'merchant');});
await test('legacy fixed deck adopted with its existing order',async()=>{const h=host({pools:[],candidates:[]});await h.run('deckCreate',{key:'old',source:'array',arrayJson:'["A","B","C"]',mode:'fixed',valueType:'text'});const order=JSON.parse(await h.run('deckPeek',{key:'old'})).values;await h.run('drawWithout',{poolId:'old',...fields});assert.equal(h.values.get('value'),order[0]);assert.equal(JSON.parse(await h.run('deckDraw',{key:'old'}))[0],order[1]);const peek=JSON.parse(await h.run('deckPeek',{key:'old'}));assert.equal(peek.remaining,1);assert.equal(peek.drawn,2);assert.equal(h.state().pools[0].legacy.history,'unknown');});
await test('legacy reset and recreate do not leave a second state',async()=>{const h=host({pools:[]});await h.run('deckCreate',{key:'old',source:'array',arrayJson:'["A","B"]',mode:'fixed',valueType:'text'});await h.run('drawWithout',{poolId:'old'});assert.equal(await h.run('deckReset',{key:'old'}),true);assert.equal(await h.run('deckCreate',{key:'old',source:'array',arrayJson:'["C"]',mode:'fixed',valueType:'text'}),1);await h.run('drawWithout',{poolId:'old',...fields});assert.equal(h.values.get('value'),'C');});
await test('player selection consumes only chosen candidate and ignores duplicate callback',async()=>{const h=host();h.onShow(async ui=>{assert.equal(ui.choices.length,2);await ui.onSelect(1);await ui.onSelect(1);});await h.run('playerChoice',{poolId:'events',...fields});assert.equal(h.values.get('value'),'B');assert.equal(h.state().pools[0].items[1].remaining,0);assert.equal(h.state().pools[0].items[0].remaining,10);assert.equal(h.state().pendingChoices.length,0);});
await test('player choice on replacement pool does not consume quantity',async()=>{const h=host({pools:[{...spec,kind:'with'}]});h.onShow(ui=>ui.onSelect(0));await h.run('playerChoice',{poolId:'events',...fields});assert.equal(h.values.get('value'),'A');assert.equal(h.state().pools[0].items[0].remaining,0);assert.equal(h.state().receipts.length,0);});
await test('player choice does not reveal excluded candidates',async()=>{const h=host({candidates:[{...rows[0],condition:'gate'}]},undefined,{gate:false});h.onShow(()=>{throw Error('must not show any UI')});await h.run('playerChoice',{poolId:'events',...fields});assert.equal(h.values.get('status'),'empty');assert.equal(h.shown,undefined);});
await test('stale candidate condition is rechecked when selecting',async()=>{const h=host({candidates:[{...rows[0],condition:'gate'}]});h.onShow(async ui=>{h.values.set('gate',false);await ui.onSelect(0);});await h.run('playerChoice',{poolId:'events',...fields});assert.equal(h.values.get('status'),'error');assert.equal(h.state().pools[0].items[0].remaining,10);assert.equal(h.state().pendingChoices.length,0);});
await test('closing choice without selection does not consume',async()=>{const h=host();h.onShow(()=>h.ctx.system.close());await h.run('playerChoice',{poolId:'events',...fields});assert.equal(h.values.get('status'),'skipped');assert.equal(h.state().pools[0].items[0].remaining,10);});
await test('choice saves pending request and resumes it in a new owner',async()=>{const h=host();let saved;h.onShow(()=>{saved=h.snapshot();h.abort.abort();});await h.run('playerChoice',{poolId:'events',requestKey:'choose',consumption:'deferred',...fields});assert.equal(P.decode(saved.poolStateV3).pendingChoices.length,1);const loaded=host({},saved);loaded.onShow(ui=>ui.onSelect(0));await loaded.immediate('playerChoice',{poolId:'events',requestKey:'choose',...fields});assert.equal(loaded.values.get('status'),'ok');assert.equal(loaded.state().pools[0].items[0].reserved,1);assert.equal(loaded.state().pendingChoices.length,0);});
await test('completed player choice replay never reopens UI',async()=>{const h=host();let shown=0;h.onShow(ui=>{shown++;return ui.onSelect(0)});await h.run('playerChoice',{poolId:'events',...fields});const before=h.snapshot();await h.immediate('playerChoice',{poolId:'events',...fields});assert.equal(shown,1);assert.deepEqual(h.snapshot(),before);});
await test('unsupported choice host reports limitation without initializing',async()=>{const h=host();delete h.ctx.system;await h.run('playerChoice',{poolId:'events',...fields});assert.equal(h.values.get('status'),'error');assert.equal(h.saved.get('poolStateV3'),'');});
await test('slot corruption is not silently reset',async()=>{const h=host({}, {poolStateV3:'{"schemaVersion":99}',drawDecks:[],fixedResults:[]});await h.run('drawWithout',{poolId:'events',...fields});assert.equal(h.saved.get('poolStateV3'),'{"schemaVersion":99}');assert.equal(h.values.get('status'),'error');});
await test('all false batch conditions skip without initialization',async()=>{const h=host({adjustments:[{batchId:'skip',op:'enable',candidateId:'a',when:'gate'}]},undefined,{gate:false});await h.run('poolUpdate',{action:'batch-adjust',batchId:'skip',poolId:'events',...fields});assert.equal(h.saved.get('poolStateV3'),'');assert.equal(h.values.get('status'),'skipped');});
await test('manual choice includes zero weight candidates',async()=>{const h=host({candidates:rows.map(r=>({...r,rate:'0'}))});h.onShow(p=>p.onSelect(0));await h.run('playerChoice',{poolId:'events',...fields});assert.equal(h.shown.choices.length,2);assert.equal(h.values.get('status'),'ok');assert.equal(h.state().pools[0].items[0].remaining,9);});
await test('choice abort preserves pending without consumption',async()=>{const h=host();h.onShow(()=>h.abort.abort());await h.run('playerChoice',{poolId:'events',...fields});assert.equal(h.state().pendingChoices.length,1);assert.equal(h.state().pools[0].items[0].remaining,10);assert.equal(h.values.get('value'),'old');});
await test('import controls follow action directly',()=>{for(const [key,f]of Object.entries(E.poolUpdate.schema))if(key.includes('__'))assert.deepEqual(f.visibleWhen,{field:'action',equals:key.split('__')[0]});});
await test('invalid condition adjustment rolls back',async()=>{const h=host();await h.run('poolUpdate',{poolId:'events',action:'initialize'});const before=h.snapshot();await h.run('poolUpdate',{poolId:'events',action:'set-condition',candidateId:'a',condition:'absent',...fields});assert.equal(h.values.get('status'),'error');assert.deepEqual(h.snapshot(),before);});
await test('non boolean import enabled is rejected',()=>assert.throws(()=>pure({},[{id:'a',enabled:'false'}]),/布尔/));
const examples=JSON.parse(fs.readFileSync(new URL('../docs/examples-v3.json',import.meta.url),'utf8'));
for(const call of examples.calls){await test('documented example '+call.method,async()=>{
 const defaults=Object.fromEntries(Object.entries(examples.variables).map(([name,type])=>[name,type==='number'?0:type==='boolean'?false:'']));
 const h=host(examples.settings,undefined,{...defaults,event_completed:true,archive_open:true,'攻击':20,'编号':7});
 h.onShow(p=>p.onSelect(0));
 const names={'draw-replace':'drawReplace','draw-without':'drawWithout','player-choice':'playerChoice','pool-update':'poolUpdate','calc':'calc'};
 assert.ok(names[call.method],`Unmapped documented method: ${call.method}`);
 const value=await h.run(names[call.method],call.params);
 if(call.method==='calc'){
  const expected={damage:26,cycle:3};assert.ok(Object.hasOwn(expected,call.params.outVar));
  assert.equal(value,expected[call.params.outVar]);assert.equal(h.values.get(call.params.outVar),value);
  assert.equal(h.values.get('ok'),true);assert.equal(h.values.get('error'),'');
 }else assert.equal(h.values.get('status'),'ok');
});}
await test('fixed multi-candidate progress survives restore independently of global RNG',async()=>{
 const config={pools:[{...spec,kind:'with'}],candidates:rows.map(x=>({...x,rate:'1'}))};
 const h=host(config);await h.run('poolUpdate',{poolId:'events',action:'initialize'});const saved=h.snapshot();
 await h.run('drawReplace',{poolId:'events',count:12,...fields});const expected=h.values.get('values'),after=h.snapshot();
 Math.random=()=>.999;const loaded=host(config,saved);await loaded.run('drawReplace',{poolId:'events',count:12,...fields});
 assert.equal(loaded.values.get('values'),expected);assert.deepEqual(loaded.snapshot(),after);
 const independent=host(config,saved);await independent.run('drawReplace',{poolId:'events',count:2,...fields});assert.notDeepEqual(independent.snapshot(),loaded.snapshot());assert.deepEqual(h.snapshot(),after);
});
await test('fresh draws use new RNG but can repeat the same result',async()=>{
 const config={pools:[{...spec,kind:'with',random:'fresh'}]};const h=host(config);await h.run('poolUpdate',{poolId:'events',action:'initialize'});const saved=h.snapshot();
 Math.random=()=>.1;await h.run('drawReplace',{poolId:'events',...fields});assert.equal(h.values.get('id'),'a');
 const loaded=host(config,saved);Math.random=()=>.9;await loaded.run('drawReplace',{poolId:'events',...fields});assert.equal(loaded.values.get('id'),'b');
 Math.random=()=>.9;await loaded.run('drawReplace',{poolId:'events',...fields});assert.equal(loaded.values.get('id'),'b');
});
await test('inspection preserves initialized RNG and pending receipts',async()=>{
 const h=host();await h.run('drawWithout',{poolId:'events',consumption:'deferred',...fields});const saved=h.snapshot();
 const report=readInspection(h.owner,h.ctx,'events');assert.equal(report.status,'ok');await h.run('poolUpdate',{poolId:'events',action:'inspect',...fields});assert.deepEqual(h.snapshot(),saved);
});
await test('filtered choice indexes map to stable IDs even with duplicate labels',async()=>{
 const h=host({candidates:[{...rows[0],id:'excluded',condition:'blocked'},{...rows[0],id:'first',label:'same'},{...rows[0],id:'last',label:'same'}]},undefined,{blocked:false});
 h.onShow(async ui=>{assert.deepEqual(ui.choices.map(x=>x.originalIndex),[0,1]);await ui.onSelect(1);await ui.onSelect(0);});
 await h.run('playerChoice',{poolId:'events',...fields});assert.equal(h.values.get('id'),'last');assert.deepEqual(h.state().pools[0].items.map(x=>x.remaining),[10,10,9]);
});
await test('choice revalidates availability after an intervening adjustment',async()=>{
 const h=host();h.onShow(async ui=>{await h.run('poolUpdate',{poolId:'events',action:'set-quantity',candidateId:'a',amount:'0'});await ui.onSelect(0);});
 await h.run('playerChoice',{poolId:'events',...fields});assert.equal(h.values.get('status'),'error');assert.equal(h.values.get('value'),'old');assert.equal(h.state().pools[0].items[0].remaining,0);assert.equal(h.state().pendingChoices.length,0);
});
Math.random=original;
console.warn=warn;console.log(JSON.stringify({passed,failed,scope:'v3 deterministic/state/SDK-shim tests; not real Studio/player'}));if(failed)process.exitCode=1;
